services:
  app:
    build:
      context: .
      args:
        - DEBUG=true
        - DEV=true
    ports:
      - "5005:5005"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:5005"